version: '3.1'

services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog_strapi_api
      PGDATA: /var/lib/postgresql/data/PGDATA
    volumes:
      - C:/Users/Hitss/PostgressData:/var/lib/postgresql/data/PGDATA
    ports:
      - 5432:5432